// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var getCanvas = ( (id) => document.getElementById(id) );

exports.getCanvas = getCanvas;
/* getCanvas Not a pure module */
