// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Subs$Jesse = require("./Subs.bs.js");
var BaseGame$Jesse = require("./BaseGame.bs.js");

var clockFrames = Subs$Jesse.create("clock", (function (consumer) {
        var id = [0];
        var keepAnimation = function (time) {
          Curry._1(consumer, time);
          id[0] = window.requestAnimationFrame(keepAnimation);
          return /* () */0;
        };
        id[0] = window.requestAnimationFrame(keepAnimation);
        return (function () {
            window.cancelAnimationFrame(id[0]);
            return /* () */0;
          });
      }));

var initM = /* tuple */[
  0,
  /* Empty */0
];

function u(e, m) {
  return /* tuple */[
          m + e,
          /* Empty */0
        ];
}

function sub() {
  return clockFrames;
}

function render(m) {
  console.log("Hola " + Pervasives.string_of_float(m));
  return /* () */0;
}

BaseGame$Jesse.runGame(u, render, sub, initM);

var Main = /* module */[
  /* clockFrames */clockFrames,
  /* initM */initM,
  /* u */u,
  /* sub */sub,
  /* render */render
];

exports.Main = Main;
/* clockFrames Not a pure module */
