// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Subscription$Jesse = require("./Subscription.bs.js");

var animationSub = Subscription$Jesse.create("animationSub", (function (consumer) {
        var id = [0];
        var keepAnimation = function (time) {
          Curry._1(consumer, time);
          id[0] = window.requestAnimationFrame(keepAnimation);
          return /* () */0;
        };
        id[0] = window.requestAnimationFrame(keepAnimation);
        return (function () {
            window.cancelAnimationFrame(id[0]);
            return /* () */0;
          });
      }));

console.log("Hello, BuckleScript and Reason!");

function runGame(_, _$1, _$2, _$3) {
  return 1;
}

exports.animationSub = animationSub;
exports.runGame = runGame;
/* animationSub Not a pure module */
