// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var getWorld = ( (engine) => engine.world );

var Engine = /* module */[/* getWorld */getWorld];

var World = /* module */[];

var Bodies = /* module */[];

exports.Engine = Engine;
exports.World = World;
exports.Bodies = Bodies;
/* getWorld Not a pure module */
