// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var getView = ( (app) => app.view );

var Application = /* module */[/* getView */getView];

var Container = /* module */[];

var Graphics = /* module */[];

var Sprite = /* module */[];

var Utils = /* module */[];

exports.Application = Application;
exports.Container = Container;
exports.Graphics = Graphics;
exports.Sprite = Sprite;
exports.Utils = Utils;
/* getView Not a pure module */
