// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function create(id, body) {
  return /* record */[
          /* id */id,
          /* run */Curry.__1(body)
        ];
}

exports.create = create;
/* No side effect */
