// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function single(id, x) {
  return /* NonEmpty */Block.__(0, [
            id,
            (function (sub) {
                Curry._1(sub, x);
                return (function () {
                    return /* () */0;
                  });
              })
          ]);
}

function create(id, body) {
  return /* NonEmpty */Block.__(0, [
            id,
            body
          ]);
}

function run(_subtion, subber) {
  while(true) {
    var subtion = _subtion;
    if (typeof subtion === "number") {
      return (function () {
          return /* () */0;
        });
    } else if (subtion.tag) {
      run(subtion[0], subber);
      _subtion = subtion[1];
      continue ;
    } else {
      return Curry._1(subtion[1], subber);
    }
  };
}

exports.single = single;
exports.create = create;
exports.run = run;
/* No side effect */
