// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function from(x, func) {
  Curry._1(func, x);
  return (function () {
      console.log("Cancelling");
      return /* () */0;
    });
}

exports.from = from;
/* No side effect */
